Repository osu-tournament-rating/otr-api, pull requests merged in 2024-09, with the labels that each got.

#370 Adjust MatchGameCountCheck to be more accurate
  DataWorkerService.Tests/AutomationChecks/Matches/MatchGameCountCheckTests.cs
  DataWorkerService/AutomationChecks/Matches/MatchGameCountCheck.cs
Labels: bug, size/M

#382 Update staging and prod deployment cfg file paths
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#383 Update source file pathing
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#384 Generate migrations script on deploy
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
  API/Program.cs
  Database/OtrDbContextFactory.cs
Labels: size/M

#385 Install dotnet ef
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#386 Fix migrations
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#387 Use -o instead of piping migrations output
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#398 Remove `RatingAdjustmentsService` & `RatingAdjustmentsRepository`
  API/Controllers/StatsController.cs
  API/Program.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Implementations/RatingAdjustmentsesService.cs
  API/Services/Interfaces/IPlayerStatsService.cs
  API/Services/Interfaces/IRatingAdjustmentsService.cs
  Database/Repositories/Implementations/RatingAdjustmentsRepository.cs
  Database/Repositories/Interfaces/IRatingAdjustmentsRepository.cs
Labels: size/L

#402 redirect old links to their respective new links
  API/Program.cs
  Database/Entities/Processor/PlayerRating.cs
  Database/Entities/Processor/RatingAdjustment.cs
  README.md
Labels: type:documentation, size/S

#403 Improve processors
  DataWorkerService.Tests/AutomationChecks/IntegratedAutomationChecksTests.cs
  DataWorkerService.Tests/AutomationChecks/Matches/MatchHeadToHeadCheckTests.cs
  DataWorkerService.Tests/AutomationChecks/Matches/MatchNameCheckTests.cs
  DataWorkerService.Tests/DataWorkerService.Tests.csproj
  DataWorkerService.Tests/Mocks/MockContext.cs
  DataWorkerService.Tests/Mocks/MockResolvers.cs
  DataWorkerService.Tests/Stats/GameStatsProcessorTests.cs
  DataWorkerService.Tests/Stats/MatchStatsProcessorTests.cs
  DataWorkerService.Tests/Utilities/MatchCostCalculatorTests.cs
  DataWorkerService/AutomationChecks/Constants.cs
  DataWorkerService/AutomationChecks/Matches/MatchHeadToHeadCheck.cs
  DataWorkerService/AutomationChecks/Matches/MatchNameCheck.cs
  DataWorkerService/Configurations/OsuConfiguration.cs
  DataWorkerService/Processors/Games/GameAutomationChecksProcessor.cs
  DataWorkerService/Processors/Games/GameStatsProcessor.cs
  DataWorkerService/Processors/Games/GameVerificationProcessor.cs
  DataWorkerService/Processors/Matches/MatchAutomationChecksProcessor.cs
  DataWorkerService/Processors/Matches/MatchDataProcessor.cs
  DataWorkerService/Processors/Matches/MatchStatsProcessor.cs
  DataWorkerService/Processors/Matches/MatchVerificationProcessor.cs
  DataWorkerService/Processors/Resolvers/Implementations/GameProcessorResolver.cs
  DataWorkerService/Processors/Resolvers/Implementations/MatchProcessorResolver.cs
  DataWorkerService/Processors/Resolvers/Implementations/ProcessorResolver.cs
  DataWorkerService/Processors/Resolvers/Implementations/ScoreProcessorResolver.cs
  DataWorkerService/Processors/Resolvers/Implementations/TournamentProcessorResolver.cs
  DataWorkerService/Processors/Resolvers/Interfaces/IProcessorResolver.cs
  DataWorkerService/Processors/Scores/ScoreAutomationChecksProcessor.cs
  DataWorkerService/Processors/Scores/ScoreVerificationProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentAutomationChecksProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentDataProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentStatsProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentVerificationProcessor.cs
  DataWorkerService/Program.cs
  DataWorkerService/Services/Implementations/OsuApiDataParserService.cs
  DataWorkerService/Utilities/MatchCostCalculator.cs
  Database/Enums/Verification/GameRejectionReason.cs
  Database/Enums/Verification/MatchRejectionReason.cs
  Database/Enums/Verification/ScoreRejectionReason.cs
  Database/Migrations/20240911003913_Move_OsuRulesetData_ToOwnTable.cs
  Database/OtrContext.cs
  Database/Repositories/Implementations/BeatmapsRepository.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/IBeatmapsRepository.cs
  Database/Repositories/Interfaces/IPlayersRepository.cs
  OsuApiClient/Configurations/Implementations/OsuClientConfiguration.cs
  OsuApiClient/Configurations/Interfaces/IOsuClientConfiguration.cs
  OsuApiClient/Domain/Osu/Beatmaps/BeatmapExtended.cs
  OsuApiClient/Domain/Osu/Multiplayer/MultiplayerGame.cs
  OsuApiClient/Net/Authorization/FixedWindowRateLimit.cs
  OsuApiClient/Net/JsonModels/Osu/Beatmaps/BeatmapExtendedJsonModel.cs
  OsuApiClient/Net/JsonModels/Osu/Multiplayer/GameScoreJsonModel.cs
  OsuApiClient/Net/JsonModels/Osu/Multiplayer/MultiplayerGameJsonModel.cs
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
  TestingUtils/SeededData/SeededMatch.cs
  otrAPI.sln.DotSettings
Labels: size/XXL, type:testing, epic, type:performance, project:DataWorkerService, project:Database

#399 Include ProcessingStatus & VerificationStatus in TournamentDTO
  API/DTOs/TournamentDTO.cs
Labels: size/S

#407 Rewrite matches navigation inclusion query extensions
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IMatchesService.cs
  Database/Enums/QueryFilterType.cs
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Repositories/Interfaces/IMatchesRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/L, area:matches, project:API

#406 Add `HTTP PATCH` endpoints for `Match`, `Game`, and `GameScore`
  API/Controllers/GameScoresController.cs
  API/Controllers/GamesController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/TournamentsController.cs
  API/DTOs/GameDTO.cs
  API/DTOs/GameScoreDTO.cs
  API/Program.cs
  API/Services/Implementations/GameScoresService.cs
  API/Services/Implementations/GamesService.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IGameScoresService.cs
  API/Services/Interfaces/IGamesService.cs
  API/Services/Interfaces/IMatchesService.cs
  Database/Repositories/Implementations/GamesRepository.cs
  Database/Repositories/Interfaces/IGamesRepository.cs
Labels: size/L, area:matches

#413 Update DataWorkerService example.appsettings.json
  DataWorkerService/example.appsettings.json
Labels: size/S, config-change, project:DataWorkerService

#412 Change naming of all screening classes/fields/strings to filtering
  API/Controllers/FilteringController.cs
  API/DTOs/FilteringRequestDTO.cs
  API/DTOs/FilteringResultDTO.cs
  API/DTOs/PlayerFilteringResultDTO.cs
  API/DTOs/ScreeningResultDTO.cs
  API/Program.cs
  API/Services/Implementations/FilteringService.cs
  API/Services/Implementations/ScreeningService.cs
  API/Services/Interfaces/IFilteringService.cs
  API/Services/Interfaces/IScreeningService.cs
  Database/Enums/FilteringFailReason.cs
  Database/Enums/FilteringResult.cs
  Database/Enums/ScreeningResult.cs
Labels: api:breaking-change, size/L, area:filtering, project:API

#415 DataWorker fix a crash for tournaments with no matches
  DataWorkerService/BackgroundServices/TournamentProcessorService.cs
Labels: size/XS

#405 Tournament verification query param
  API/Controllers/TournamentsController.cs
  API/Services/Implementations/TournamentsService.cs
  API/Services/Interfaces/ITournamentsService.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
Labels: size/M

#422 Fix ordering / missing interface
  Database/Entities/Match.cs
  Database/Entities/Tournament.cs
Labels: size/XS

#427 Include rejection reason in TournamentDTO
  API/DTOs/TournamentDTO.cs
Labels: size/XS

#429 Database this should fix infinite / blank audits
  Database/Entities/AuditEntityBase.cs
  Database/Entities/Interfaces/IAuditEntity.cs
  Database/Interceptors/AuditingInterceptor.cs
  Database/Utilities/AuditingUtils.cs
Labels: size/M

#430 Add --startup-project API to migrations script
  .github/workflows/staging-deploy.yml
Labels: size/XS

#425 Create `TAdminNoteEntity` repository base
  Database/Repositories/Implementations/AdminNoteRepositoryBase.cs
  Database/Repositories/Interfaces/IAdminNoteRepository.cs
Labels: size/M

#432 re-add OtrDbContextFactory with appsettings import & exception handling
  Database/Database.csproj
  Database/OtrDbContextFactory.cs
Labels: size/M, project:Database

#431 Access layer for admin notes
  API/DTOs/AdminNoteDTO.cs
  API/Services/Implementations/AdminNoteService.cs
  API/Services/Interfaces/IAdminNoteService.cs
  Database/Repositories/Implementations/AdminNoteRepositoryBase.cs
  Database/Repositories/Interfaces/IAdminNoteRepository.cs
Labels: type:feature, size/L, area:admin, project:API

#434 Improve swagger doc generation
  API/API.csproj
  API/Middlewares/RequestLoggingMiddleware.cs
  API/Program.cs
  API/SwaggerGen/BitwiseFlagEnumSchemaFilter.cs
  Database/Database.csproj
  Database/Entities/AuditEntityBase.cs
Labels: type:documentation, size/L, project:API

#441 Deploy using postgres 16
  cfg/docker-compose-prod.yml
  cfg/docker-compose-staging.yml
Labels: size/XS

#443 Use oriented deisgn in `PlayersController`
  API/Controllers/PlayersController.cs
Labels: api:breaking-change, size/XS, project:API
