Repository osu-tournament-rating/otr-api, pull requests merged in 2024-10, with the labels that each got.

#444 Refactor usage of `claim` to `role` in the context of JWT
  API.Tests/Utilities/ClaimsPrincipalExtensionsTests.cs
  API.Tests/Utilities/OtrClaimsTests.cs
  API.Tests/Utilities/RateLimitOverridesSerializerTests.cs
  API/Authorization/AuthorizationPolicies.cs
  API/Authorization/OtrClaims.cs
  API/Authorization/RateLimitOverridesSerializer.cs
  API/Controllers/BeatmapsController.cs
  API/Controllers/ClientsController.cs
  API/Controllers/FilteringController.cs
  API/Controllers/GameScoresController.cs
  API/Controllers/GamesController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/SearchController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Controllers/UsersController.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Utilities/Extensions/ClaimsPrincipalExtensions.cs
  API/Utilities/OtrClaims.cs
Labels: type:documentation, size/L, type:code-quality, project:API

#453 Strip query string from tournament submission forum urls
  API/Controllers/TournamentsController.cs
Labels: size/XS

#452 Use `appsettings.Development.json` for debug design time operations
  Database/OtrDbContextFactory.cs
Labels: size/XS

#436 Add tournament pagination
  API/Controllers/TournamentsController.cs
  API/DTOs/TournamentRequestQueryDTO.cs
  API/Services/Implementations/LeaderboardService.cs
  API/Services/Implementations/TournamentsService.cs
  API/Services/Interfaces/ILeaderboardService.cs
  API/Services/Interfaces/ITournamentsService.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
Labels: api:breaking-change, size/L, area:tournaments, project:API

#445 OAuth security and code quality overhaul
  API.Tests/Utilities/ClaimsPrincipalExtensionsTests.cs
  API.Tests/Utilities/OtrClaimsTests.cs
  API/Authorization/DefaultTokenValidationParameters.cs
  API/Authorization/Handlers/AccessUserResourcesAuthorizationHandler.cs
  API/Authorization/OtrClaims.cs
  API/Configurations/JwtConfiguration.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/TournamentsController.cs
  API/Controllers/UsersController.cs
  API/DTOs/AccessCredentialsDTO.cs
  API/DTOs/DetailedResponseDTO.cs
  API/DTOs/OAuthResponseDTO.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Handlers/Interfaces/IOAuthHandler.cs
  API/Middlewares/RequestLoggingMiddleware.cs
  API/Middlewares/WhitelistEnforcementMiddleware.cs
  API/Program.cs
  API/Services/Implementations/JwtService.cs
  API/Services/Interfaces/IJwtService.cs
  API/Utilities/Extensions/ClaimsPrincipalExtensions.cs
Labels: bug, size/XL, type:code-quality, area:login, config-change, area:oauth, project:API

#455 Utility console app for generating and validating JWTs in development
  API.Utils.Jwt/API.Utils.Jwt.csproj
  API.Utils.Jwt/Options/GeneratorOptions.cs
  API.Utils.Jwt/Options/JwtUtilsOptionsBase.cs
  API.Utils.Jwt/Options/OptionsExtensions.cs
  API.Utils.Jwt/Options/ReadOptions.cs
  API.Utils.Jwt/Program.cs
  API/Authorization/OtrClaims.cs
  API/Middlewares/RequestLoggingMiddleware.cs
  otrAPI.sln
Labels: size/XL

#454 More swagger improvements
  API/Authorization/OtrClaims.cs
  API/Controllers/MeController.cs
  API/Controllers/UsersController.cs
  API/Program.cs
  API/SwaggerGen/ActionSecurityOperationFilter.cs
  API/SwaggerGen/SecurityRequirements.cs
Labels: type:feature, size/L, project:API

#463 Add log file size limitation
  cfg/docker-compose-prod.yml
  cfg/docker-compose-staging.yml
Labels: size/XS

#464 fix logging key
  cfg/docker-compose-prod.yml
  cfg/docker-compose-staging.yml
Labels: size/XS

#461 Remove `system` client permission
  API.Tests/SeedData/SeededBaseStats.cs
  API.Tests/Utilities/ClaimsPrincipalExtensionsTests.cs
  API.Tests/Utilities/OtrClaimsTests.cs
  API.Tests/Utilities/RateLimitOverridesSerializerTests.cs
  API/Authorization/AuthorizationPolicies.cs
  API/Authorization/Handlers/AccessUserResourcesAuthorizationHandler.cs
  API/Authorization/OtrClaims.cs
  API/Controllers/BeatmapsController.cs
  API/Controllers/ClientsController.cs
  API/Controllers/FilteringController.cs
  API/Controllers/GamesController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/SearchController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Controllers/UsersController.cs
  API/DTOs/PlayerFilteringResultDTO.cs
  API/Middlewares/WhitelistEnforcementMiddleware.cs
  API/Program.cs
  API/Repositories/Implementations/ApiBaseStatsRepository.cs
  API/Repositories/Implementations/ApiMatchWinRecordRepository.cs
  API/Repositories/Implementations/ApiPlayerMatchStatsRepository.cs
  API/Services/Implementations/UserService.cs
  API/Utilities/Extensions/ClaimsPrincipalExtensions.cs
  DataWorkerService/AutomationChecks/Matches/MatchNameCheck.cs
Labels: api:breaking-change, size/M, type:code-quality, project:API

#468 Update qodana.yaml
  qodana.yaml
Labels: size/XS

#467 Update qodana_code_quality.yml
  .github/workflows/qodana_code_quality.yml
  qodana.sarif.json
Labels: size/XXL

#469 Remove push master qodana check
  .github/workflows/qodana_code_quality.yml
Labels: size/XS

#470 Target master by default
  qodana.sarif.json
Labels: size/XS

#471 Remove qodana baseline
  .github/workflows/qodana_code_quality.yml
  qodana.sarif.json
Labels: size/XXL

#483 Use full linter
  .github/workflows/qodana_code_quality.yml
  qodana.yaml
Labels: size/XS

#465 Remove OsuSharp
  API/API.csproj
  API/Configurations/AuthConfiguration.cs
  API/Configurations/OsuConfiguration.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Program.cs
  OsuApiClient/OsuClient.cs
Labels: size/M, config-change, area:oauth, project:API

#475 Allow tournaments to be rejected at submission
  API/Controllers/TournamentsController.cs
  API/DTOs/TournamentSubmissionDTO.cs
  API/Services/Implementations/TournamentsService.cs
Labels: type:feature, size/M, area:tournaments, area:admin, project:API

#484 Add warning flags to `MatchDTO` and `GameDTO`
  API/DTOs/GameDTO.cs
  API/DTOs/MatchDTO.cs
Labels: type:feature, size/S, project:API

#493 Fix unintended disposal of `HttpClient`
  OsuApiClient/OsuClient.cs
Labels: bug, size/XS

#485 Modify default rate limit windows
  DataWorkerService/Services/Implementations/PlayersService.cs
  OsuApiClient/Net/Authorization/FixedWindowRateLimit.cs
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
Labels: size/M, area:processing, type:performance, project:DataWorkerService

#494 Create `TournamentCompactDTO` and include it in `MatchDTO`
  API/Configurations/MapperProfile.cs
  API/DTOs/MatchDTO.cs
  API/DTOs/TournamentCompactDTO.cs
  API/DTOs/TournamentDTO.cs
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/L

#495 Add `AdminNotes` to `MatchDTO`
  API/DTOs/MatchDTO.cs
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/S

#497 Add `AdminNotes` to `GameDTO`
  API/DTOs/GameDTO.cs
  Database/Repositories/Implementations/GamesRepository.cs
  Database/Repositories/Interfaces/IGamesRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/M

#498 Create new `RateLimitOverrides` on `OAuthClient` creation
  API/Services/Implementations/OAuthClientService.cs
Labels: size/XS, project:API

#511 Add `JetBrains.Annotations` package
  API/API.csproj
  DataWorkerService/DataWorkerService.csproj
  Database/Database.csproj
Labels: size/XS, type:code-quality, project:API, project:DataWorkerService, project:Database

#499 Update example.appsettings.json
  API/example.appsettings.json
Labels: size/XS

#506 Tournament deletion functionality
  API/Controllers/TournamentsController.cs
  API/Services/Implementations/TournamentsService.cs
  API/Services/Interfaces/ITournamentsService.cs
Labels: type:feature, size/M

#500 Include admin notes in GameScoreDTO
  API/DTOs/GameScoreDTO.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/S

#502 Fix invalid entity field type & fix OAuth issues
  API/Handlers/Implementations/OAuthHandler.cs
  API/Middlewares/WhitelistEnforcementMiddleware.cs
  API/Services/Implementations/JwtService.cs
  Database/Entities/OAuthClient.cs
Labels: bug, size/S, area:oauth

#507 Match deletion functionality
  API/Controllers/MatchesController.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IMatchesService.cs
Labels: size/M

#508 Game deletion functionality
  API/Controllers/GamesController.cs
  API/Services/Implementations/GamesService.cs
  API/Services/Interfaces/IGamesService.cs
Labels: type:feature, size/M

#509 Score deletion functionality
  API/Controllers/GameScoresController.cs
  API/Services/Implementations/GameScoresService.cs
  API/Services/Interfaces/IGameScoresService.cs
Labels: type:feature, size/M, project:API, area:scores

#512 Implement match name format warning check
  DataWorkerService.Tests/AutomationChecks/Matches/MatchNameFormatCheckTests.cs
  DataWorkerService.Tests/AutomationChecks/Matches/MatchNamePrefixCheckTests.cs
  DataWorkerService.Tests/Mocks/MockResolvers.cs
  DataWorkerService/AutomationChecks/Constants.cs
  DataWorkerService/AutomationChecks/Matches/MatchNameFormatCheck.cs
  DataWorkerService/AutomationChecks/Matches/MatchNamePrefixCheck.cs
  DataWorkerService/Program.cs
  Database/Enums/Verification/MatchRejectionReason.cs
  Database/Enums/Verification/MatchWarningFlags.cs
  TestingUtils/SeededData/SeededMatch.cs
Labels: type:feature, size/M, type:testing, area:matches, project:DataWorkerService

#505 Add support for sorting tournaments by various keys
  API/DTOs/MatchesFilterDTO.cs
  API/DTOs/TournamentRequestQueryDTO.cs
  API/Services/Implementations/TournamentsService.cs
  Database/Enums/Queries/MatchQuerySortType.cs
  Database/Enums/TournamentQuerySortType.cs
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/IMatchesRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/L

#514 Fix and improve API rate limiting
  API/Middlewares/RateLimitHeadersMiddleware.cs
  API/Program.cs
Labels: bug, size/L, type:code-quality, project:API

#520 Disable Qodana PR comment, add fail threshold of 0
  .github/workflows/qodana_code_quality.yml
Labels: size/XS, type:code-quality

#513 Implement match game count warning check
  DataWorkerService.Tests/AutomationChecks/Matches/MatchGameCountCheckTests.cs
  DataWorkerService/AutomationChecks/Matches/MatchGameCountCheck.cs
Labels: type:feature, size/M, type:testing, area:matches, project:DataWorkerService
