Repository osu-tournament-rating/otr-api, pull requests merged in 2024-03, with the labels that each got.

#137 Update readme to point to otr-wiki
  README.md
Labels: documentation, size/XS

#143 Pre-OAuth
  API/API.csproj
  API/BackgroundWorkers/OsuTrackApiWorker.cs
  API/Configurations/ConnectionStringsConfiguration.cs
  API/Configurations/Credentials.cs
  API/Configurations/ICredentials.cs
  API/Configurations/JwtConfiguration.cs
  API/Configurations/OsuConfiguration.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/LoginController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/DTOs/AggregatePlayerMatchStatsDTO.cs
  API/Osu/Multiplayer/OsuApiService.cs
  API/OtrContext.cs
  API/Program.cs
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Interfaces/IMatchesService.cs
  API/Services/Interfaces/IPlayerStatsService.cs
  API/Utilities/ConfigurationExtensions.cs
  API/Utilities/QueryExtensions.cs
  API/example.appsettings.json
  APITests/MockRepositories/MockPlayerRepository.cs
  APITests/TestDatabaseFixture.cs
  README.md
Labels: size/XL

#140 Support Api Versioning
  API/API.csproj
  API/Controllers/BeatmapsController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Program.cs
Labels: type:feature, priority:2, api:breaking-change, size/M

#153 Remove unused ambiguous methods
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IPlayerService.cs
Labels: bug, size/M

#147 Update roles across all controllers, remove redundant endpoints
  API/Controllers/BeatmapsController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Program.cs
  API/Utilities/ClaimsPrincipalExtensions.cs
  API/Utilities/HttpContextExtensions.cs
  APITests/Utilities/ClaimsPrincipalExtensionsTests.cs
Labels: size/L

#156 Fix styling
  .config/dotnet-tools.json
  .csharpierignore
  .csharpierrc
  .editorconfig
  .github/workflows/ci.yml
  API/ModelBinders/LeaderboardFilterModelBinder.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Utilities/MathUtils.cs
Labels: size/M, type:code-quality

#158 Fix role extension methods
  API/Utilities/ClaimsPrincipalExtensions.cs
  API/Utilities/HttpContextExtensions.cs
  APITests/Utilities/ClaimsPrincipalExtensionsTests.cs
Labels: bug, priority:0, size/M

#159 Hotfix/ci
  .github/workflows/ci.yml
Labels: size/XXL, size/XS

#155 Return `T` instead of `T?` in `RepositoryBase.CreateAsync()`
  API/Handlers/Implementations/OAuthHandler.cs
  API/Handlers/Interfaces/IOAuthHandler.cs
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/RepositoryBase.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Implementations/UserRepository.cs
  API/Repositories/Interfaces/IRepository.cs
  API/Services/Implementations/OAuthClientService.cs
  API/Services/Interfaces/IOAuthClientService.cs
Labels: size/M, type:code-quality

#150 Remove aggressive clockskew
  API/Program.cs
Labels: size/XS

#160 Develop
  .config/dotnet-tools.json
  .csharpierignore
  .csharpierrc
  .editorconfig
  .github/workflows/ci.yml
  API/Controllers/BeatmapsController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Handlers/Interfaces/IOAuthHandler.cs
  API/ModelBinders/LeaderboardFilterModelBinder.cs
  API/Program.cs
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/RepositoryBase.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Implementations/UserRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Repositories/Interfaces/IRepository.cs
  API/Services/Implementations/OAuthClientService.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IOAuthClientService.cs
  API/Services/Interfaces/IPlayerService.cs
  API/Utilities/ClaimsPrincipalExtensions.cs
  API/Utilities/HttpContextExtensions.cs
  API/Utilities/MathUtils.cs
  APITests/Utilities/ClaimsPrincipalExtensionsTests.cs
Labels: size/L

#164 Fix `/players/{id}/info` regression
  API/Controllers/MeController.cs
  API/Controllers/PlayersController.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IPlayerService.cs
Labels: size/M

#171 Add whitelist perms to all controllers
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
Labels: size/S

#167 Use proper `ClaimsPrincipal` when identifying refresh token scopes
  API/Controllers/OAuthController.cs
  API/Handlers/Implementations/OAuthHandler.cs
Labels: bug, size/M, type:code-quality

#168 Add versatile player fetching
  API/Controllers/PlayersController.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IPlayerService.cs
Labels: size/M, type:code-quality, area:players

#174 Fix roles for real this time
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
Labels: size/S

#175 Develop
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IPlayerService.cs
Labels: size/L

#176 Staging
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IPlayerService.cs
Labels: size/L

#177 Correct all controllers' role authorization schemes
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
Labels: bug, priority:0, size/S

#178 Update role parsing in `ClaimsPrincipalExtensions`
  API/Handlers/Implementations/OAuthHandler.cs
  API/Utilities/ClaimsPrincipalExtensions.cs
  APITests/Utilities/ClaimsPrincipalExtensionsTests.cs
Labels: bug, size/M

#183 Fix refreshed access tokens not receiving `user` or `client` claims
  API/API.csproj
  API/Controllers/MeController.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Program.cs
Labels: bug, api:breaking-change, size/M, type:code-quality

#184 Update all uses of configuration values to instead use `IOptions<T>`
  API/Configurations/AuthConfiguration.cs
  API/Configurations/ConnectionStringsConfiguration.cs
  API/Configurations/JwtConfiguration.cs
  API/Configurations/OsuConfiguration.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Program.cs
  API/example.appsettings.json
Labels: size/L, type:code-quality

#185 Fix `Jwt.Audience` not being initialized
  API/Configurations/JwtConfiguration.cs
Labels: bug, size/XS

#186 Add unique instance claim to all tokens.
  API/Handlers/Implementations/OAuthHandler.cs
Labels: bug, size/XS

#188 Disable husky for docker build
  Dockerfile
Labels: bug, size/XS

#190 Hotfix policy & allow anonymous in development
  API/Controllers/MatchesController.cs
  API/Program.cs
Labels: size/M

#194 Fix player repository search
  API/Repositories/Implementations/PlayerRepository.cs
Labels: size/XS

#197 Develop
  API/Repositories/Implementations/PlayerRepository.cs
Labels: size/XS

#201 Suppress messages & fix string comparison
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Implementations/GameWinRecordsRepository.cs
  API/Repositories/Implementations/GamesRepository.cs
  API/Repositories/Implementations/HistoryRepositoryBase.cs
  API/Repositories/Implementations/MatchDuplicateRepository.cs
  API/Repositories/Implementations/MatchRatingStatsRepository.cs
  API/Repositories/Implementations/MatchScoresRepository.cs
  API/Repositories/Implementations/MatchWinRecordRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/OAuthClientRepository.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/RatingAdjustmentsRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Implementations/UserRepository.cs
Labels: size/M

#202 Develop
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Implementations/GameWinRecordsRepository.cs
  API/Repositories/Implementations/GamesRepository.cs
  API/Repositories/Implementations/HistoryRepositoryBase.cs
  API/Repositories/Implementations/MatchDuplicateRepository.cs
  API/Repositories/Implementations/MatchRatingStatsRepository.cs
  API/Repositories/Implementations/MatchScoresRepository.cs
  API/Repositories/Implementations/MatchWinRecordRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/OAuthClientRepository.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/RatingAdjustmentsRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Implementations/UserRepository.cs
Labels: size/M

#203 Staging
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Implementations/GameWinRecordsRepository.cs
  API/Repositories/Implementations/GamesRepository.cs
  API/Repositories/Implementations/HistoryRepositoryBase.cs
  API/Repositories/Implementations/MatchDuplicateRepository.cs
  API/Repositories/Implementations/MatchRatingStatsRepository.cs
  API/Repositories/Implementations/MatchScoresRepository.cs
  API/Repositories/Implementations/MatchWinRecordRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/OAuthClientRepository.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/RatingAdjustmentsRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Implementations/UserRepository.cs
Labels: size/M

#204 Add `Created` to `TournamentDTO`
  API/DTOs/TournamentDTO.cs
Labels: size/XS, area:tournaments

#208 OAuthController refactor
  API/Controllers/OAuthController.cs
  API/Program.cs
  API/Utilities/HttpResultsOperationFilter.cs
Labels: size/L, type:code-quality, area:oauth

#212 Use error checking in pre-commit
  .husky/pre-commit
  .husky/task-runner.json
Labels: bug, size/M, type:code-quality

#210 BeatmapsController refactor
  API/Controllers/BeatmapsController.cs
  API/DTOs/BeatmapDTO.cs
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Interfaces/IBeatmapRepository.cs
  API/Services/Implementations/BeatmapService.cs
  API/Services/Interfaces/IBeatmapService.cs
  otrAPI.sln.DotSettings
Labels: api:breaking-change, size/L, type:code-quality, area:beatmaps

#214 Add ability to modify client ratelimits
  API/Configurations/MapperProfile.cs
  API/Controllers/ClientsController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/OAuthController.cs
  API/DTOs/OAuthClientDTO.cs
  API/Repositories/Implementations/OAuthClientRepository.cs
  API/Repositories/Interfaces/IOAuthClientRepository.cs
  API/Services/Implementations/OAuthClientService.cs
  API/Services/Interfaces/IOAuthClientService.cs
Labels: type:feature, size/L, area:oauth

#217 Modify leaderboard tier filter behavior to match new requirements
  API/Controllers/PlayersController.cs
  API/DTOs/LeaderboardTierFilterDTO.cs
  API/ModelBinders/LeaderboardFilterModelBinder.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Utilities/LeaderboardExtensions.cs
  API/Utilities/RatingUtils.cs
  APITests/MockRepositories/MockPlayerRepository.cs
  APITests/SeedData/SeededBaseStats.cs
  APITests/Services/LeaderboardServiceTests.cs
  APITests/Utilities/LeaderboardExtensionsTests.cs
Labels: type:feature, api:breaking-change, size/XXL, area:leaderboards, pr:blocked

#221 Sort leaderboard by global rank
  API/Services/Implementations/LeaderboardService.cs
Labels: size/XS, area:leaderboards

#189 Feature/search api
  .config/dotnet-tools.json
  .husky/pre-commit
  API/API.csproj
  API/Controllers/SearchController.cs
  API/DTOs/SearchResponseDTO.cs
  API/Program.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Repositories/Interfaces/ITournamentsRepository.cs
  API/Services/Implementations/SearchService.cs
  API/Services/Interfaces/ISearchService.cs
Labels: size/L, priority:1, epic, area:search

#213 MeController Refactor
  API/Controllers/MeController.cs
  API/DTOs/UserInfoDTO.cs
  API/Entities/User.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Repositories/Implementations/UserRepository.cs
  API/Repositories/Interfaces/IUserRepository.cs
  API/Services/Implementations/UserService.cs
  API/Services/Interfaces/IUserService.cs
Labels: api:breaking-change, size/L, type:code-quality, area:me
