Repository osu-tournament-rating/otr-api, pull requests merged in 2024-02, with the labels that each got.

#103 Add Timper and Convex to whitelist
  API/Controllers/MeController.cs
Labels: size/XS

#104 Develop
  API/Controllers/MeController.cs
  API/DTOs/MatchDTO.cs
Labels: size/XS

#105 Staging
  API/Controllers/MeController.cs
  API/DTOs/MatchDTO.cs
Labels: size/XS

#75 Rating chart updates & stat fixes
  API/DTOs/AggregatePlayerMatchStatsDTO.cs
  API/DTOs/MatchDuplicateDTO.cs
  API/DTOs/PlayerRankChartDTO.cs
  API/DTOs/PlayerRatingChartDTO.cs
  API/DTOs/PlayerRatingChartDataPointDTO.cs
  API/DTOs/PlayerStatsDTO.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Implementations/GamesRepository.cs
  API/Repositories/Implementations/MatchRatingStatsRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Interfaces/IGamesRepository.cs
  API/Repositories/Interfaces/IMatchRatingStatsRepository.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Utilities/QueryExtensions.cs
  APITests/MockRepositories/MockBaseStatsRepository.cs
  APITests/Osu/MatchAutomationChecks_Warmups.cs
Labels: p/0, api:breaking-change, size/XXL

#123 Develop
  API/DTOs/AggregatePlayerMatchStatsDTO.cs
  API/DTOs/MatchDuplicateDTO.cs
  API/DTOs/PlayerRankChartDTO.cs
  API/DTOs/PlayerRatingChartDTO.cs
  API/DTOs/PlayerRatingChartDataPointDTO.cs
  API/DTOs/PlayerStatsDTO.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Implementations/GamesRepository.cs
  API/Repositories/Implementations/MatchRatingStatsRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Interfaces/IGamesRepository.cs
  API/Repositories/Interfaces/IMatchRatingStatsRepository.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Utilities/QueryExtensions.cs
  APITests/MockRepositories/MockBaseStatsRepository.cs
  APITests/Osu/MatchAutomationChecks_Warmups.cs
Labels: size/XXL

#124 Staging
  API/DTOs/AggregatePlayerMatchStatsDTO.cs
  API/DTOs/MatchDuplicateDTO.cs
  API/DTOs/PlayerRankChartDTO.cs
  API/DTOs/PlayerRatingChartDTO.cs
  API/DTOs/PlayerRatingChartDataPointDTO.cs
  API/DTOs/PlayerStatsDTO.cs
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Implementations/GamesRepository.cs
  API/Repositories/Implementations/MatchRatingStatsRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Interfaces/IGamesRepository.cs
  API/Repositories/Interfaces/IMatchRatingStatsRepository.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Utilities/QueryExtensions.cs
  APITests/MockRepositories/MockBaseStatsRepository.cs
  APITests/Osu/MatchAutomationChecks_Warmups.cs
Labels: size/XXL

#125 Add example.appsettings.json
  API/example.appsettings.json
Labels: size/S

#126 Enforce lower-case routing
  API/Program.cs
Labels: size/XS

#127 feature/edit match validation
  API/API.csproj
  API/Controllers/MatchesController.cs
  API/Program.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IMatchesService.cs
Labels: enhancement, size/M

#132 Add configuration validation, use IOptions
  API/Configurations/ConnectionStringsConfiguration.cs
  API/Configurations/Credentials.cs
  API/Configurations/ICredentials.cs
  API/Configurations/JwtConfiguration.cs
  API/Configurations/OsuConfiguration.cs
  API/Osu/Multiplayer/OsuApiService.cs
  API/OtrContext.cs
  API/Program.cs
  API/Utilities/ConfigurationExtensions.cs
  APITests/TestDatabaseFixture.cs
Labels: size/L, code quality

#106 Refactor IPlayerRepository method names & docs
  API/BackgroundWorkers/OsuTrackApiWorker.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/LoginController.cs
  API/DTOs/AggregatePlayerMatchStatsDTO.cs
  API/Repositories/Implementations/ApiMatchRepository.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Interfaces/IPlayerStatsService.cs
  API/Utilities/QueryExtensions.cs
  APITests/MockRepositories/MockPlayerRepository.cs
Labels: size/L, code quality

#134 Adds starlightof to the whitelist
  API/Controllers/MeController.cs
Labels: size/XS
