Repository osu-tournament-rating/otr-api, pull requests merged in 2024-04, with the labels that each got.

#226 Add documentation for Beatmaps Controller
  API/Controllers/BeatmapsController.cs
  API/DTOs/BeatmapDTO.cs
Labels: type:documentation, size/M, area:beatmaps

#225 Add documentation for Me Controller
  API/Controllers/MeController.cs
  API/DTOs/AggregatePlayerMatchStatsDTO.cs
  API/DTOs/BaseStatsDTO.cs
  API/DTOs/PlayerFrequencyDTO.cs
  API/DTOs/PlayerInfoDTO.cs
  API/DTOs/PlayerModStatsDTO.cs
  API/DTOs/PlayerRatingChartDTO.cs
  API/DTOs/PlayerRatingChartDataPointDTO.cs
  API/DTOs/PlayerStatsDTO.cs
  API/DTOs/PlayerTournamentMatchCostDTO.cs
  API/DTOs/PlayerTournamentTeamSizeCountDTO.cs
  API/DTOs/RankProgressDTO.cs
  API/DTOs/TournamentStatsDTO.cs
  API/DTOs/UserInfoDTO.cs
Labels: type:documentation, size/L, area:me

#231 Feature/monitoring
  .github/workflows/ci.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
  .gitignore
  API/API.csproj
  API/Configurations/ConnectionStringsConfiguration.cs
  API/Program.cs
  API/example.appsettings.json
  Dockerfile
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-staging.yml
  otel-collector-config.yml
  prometheus.yml
Labels: size/L, config-change

#240 Fix deployment
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#241 copy missing yml files to deploy servers
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#223 TournamentsController Refactor
  .editorconfig
  API/API.csproj
  API/Configurations/MapperProfile.cs
  API/Controllers/MatchesController.cs
  API/Controllers/TournamentsController.cs
  API/DTOs/CreatedAtRouteValues.cs
  API/DTOs/CreatedResultBaseDTO.cs
  API/DTOs/Interfaces/ICreatedResult.cs
  API/DTOs/MatchCreatedResultDTO.cs
  API/DTOs/MatchDTO.cs
  API/DTOs/MatchesWebSubmissionDTO.cs
  API/DTOs/TournamentCreatedResultDTO.cs
  API/DTOs/TournamentDTO.cs
  API/DTOs/TournamentWebSubmissionDTO.cs
  API/Entities/Tournament.cs
  API/Program.cs
  API/Repositories/Implementations/RepositoryBase.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Interfaces/IRepository.cs
  API/Repositories/Interfaces/ITournamentsRepository.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Implementations/TournamentsService.cs
  API/Services/Interfaces/IMatchesService.cs
  API/Services/Interfaces/ITournamentsService.cs
  API/Utilities/ClaimsPrincipalExtensions.cs
  API/Utilities/GenerateLocationUriAction.cs
  API/Utilities/JsonPatchDocumentExtensions.cs
  API/Utilities/MappingExtensions.cs
  APITests/MockRepositories/MockTournamentsRepository.cs
  APITests/Services/LeaderboardServiceTests.cs
  otrAPI.sln.DotSettings
Labels: type:documentation, type:feature, api:breaking-change, size/XXL, type:code-quality, epic, area:matches, area:tournaments, pr:blocked

#242 Improve `/api/v1/search` to use a single query parameter for all searches
  API/Controllers/SearchController.cs
  API/Services/Implementations/SearchService.cs
  API/Services/Interfaces/ISearchService.cs
Labels: type:feature, size/M, area:search

#243 Add location service and improve search service
  API/Controllers/SearchController.cs
  API/DTOs/CreatedAtRouteValues.cs
  API/DTOs/MatchCreatedResultDTO.cs
  API/DTOs/SearchResponseCollectionDTO.cs
  API/DTOs/SearchResponseDTO.cs
  API/DTOs/TournamentCreatedResultDTO.cs
  API/Program.cs
  API/Services/Implementations/SearchService.cs
  API/Services/Implementations/UrlHelperService.cs
  API/Services/Interfaces/ISearchService.cs
  API/Services/Interfaces/IUrlHelperService.cs
  API/Utilities/CreatedAtRouteValuesHelper.cs
  API/Utilities/GenerateLocationUriAction.cs
Labels: type:feature, size/L, type:code-quality, area:search

#245 Add volume to grafana
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-staging.yml
Labels: size/S

#239 Refactor PlayerMatchStatsDTO PlayerId field to 'Id'
  API/DTOs/PlayerMatchStatsDTO.cs
  API/Services/Implementations/PlayerStatsService.cs
Labels: size/XS, type:code-quality, area:stats

#220 Add screening API
  API/Controllers/ScreeningController.cs
  API/DTOs/PlayerScreeningResultDTO.cs
  API/DTOs/ScreeningRequestDTO.cs
  API/DTOs/ScreeningResultDTO.cs
  API/Enums/ScreeningFailReason.cs
  API/Enums/ScreeningResult.cs
  API/Program.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/LeaderboardService.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Implementations/ScreeningService.cs
  API/Services/Interfaces/IBaseStatsService.cs
  API/Services/Interfaces/IPlayerService.cs
  API/Services/Interfaces/IPlayerStatsService.cs
  API/Services/Interfaces/IScreeningService.cs
  APITests/MockRepositories/MockPlayerRepository.cs
Labels: type:feature, size/L, area:screening

#251 Upgrade vulnerable packages
  API/API.csproj
Labels: size/S

#249 Remove unused methods from `MatchesRepository`
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
Labels: size/L

#248 Refactor `PlayerMatchStatsRepository.GetModStatsAsync`
  API/Osu/OsuEnums.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
Labels: size/L, type:code-quality

#252 Fix deploy scripts copying wrong file
  .github/workflows/dev-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#254 Add XML docs to `Entities.Player`
  API/Entities/Player.cs
  otrAPI.sln.DotSettings
Labels: type:documentation, size/M

#253 Requested web changes for search
  API/Configurations/MapperProfile.cs
  API/DTOs/MatchSearchResultDTO.cs
  API/DTOs/PlayerSearchResultDTO.cs
  API/DTOs/SearchResponseCollectionDTO.cs
  API/DTOs/SearchResponseDTO.cs
  API/DTOs/TournamentSearchResultDTO.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Services/Implementations/SearchService.cs
Labels: type:feature, size/L, area:search

#122 Implements Rating Util Tests
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Utilities/RatingUtils.cs
  APITests/Utilities/RatingUtilsTests.cs
Labels: size/XL, type:testing

#250 Refactor `MatchesController.EditVerificationStatus` and `MatchesRepository.UpdateVerificationStatus`
  API/BackgroundWorkers/OsuMatchDataWorker.cs
  API/Controllers/MatchesController.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IMatchesService.cs
Labels: api:breaking-change, size/L, type:code-quality, area:matches

#258 Hotfix/grafana volume name
  API/Repositories/Implementations/BaseStatsRepository.cs
  docker-compose-prod.yml
  docker-compose-staging.yml
Labels: size/S

#259 Develop
  API/Repositories/Implementations/BaseStatsRepository.cs
  docker-compose-prod.yml
  docker-compose-staging.yml
Labels: size/S

#265 Refactor `Entities.BaseStats` to use enums
  API/Entities/BaseStats.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/SearchService.cs
  API/Utilities/QueryExtensions.cs
Labels: type:documentation, size/M, type:code-quality

#269 Refactor constructor behavior of PlayerStatsDTO
  API/DTOs/PlayerStatsDTO.cs
  API/Services/Implementations/PlayerStatsService.cs
Labels: size/M

#255 Refactor `Entities.Match.VerificationStatus` and `Entities.Match.VerificationSource` to map to enums
  API/BackgroundWorkers/OsuMatchDataWorker.cs
  API/Entities/Interfaces/IHistoryEntity.cs
  API/Entities/Match.cs
  API/Entities/MatchEntityBase.cs
  API/Entities/MatchHistory.cs
  API/Entities/User.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Implementations/TournamentsService.cs
  API/Utilities/QueryExtensions.cs
  APITests/AutomationChecks/AutomationChecksTests.cs
  APITests/SeedData/SeededMatch.cs
Labels: size/L, type:code-quality

#270 Fix invalid id fetching
  API/Repositories/Implementations/MatchesRepository.cs
Labels: bug, size/S

#271 Move all `Osu/OsuEnums` into individual files at `Osu/Enums/`
  API/BackgroundWorkers/OsuPlayerDataWorker.cs
  API/BackgroundWorkers/OsuTrackApiWorker.cs
  API/Controllers/OAuthController.cs
  API/DTOs/GameDTO.cs
  API/DTOs/TournamentSearchResultDTO.cs
  API/Entities/BaseStats.cs
  API/Entities/Game.cs
  API/Entities/MatchScore.cs
  API/Entities/Player.cs
  API/Osu/AutomationChecks/AutomationConstants.cs
  API/Osu/AutomationChecks/GameAutomationChecks.cs
  API/Osu/Enums/Mods.cs
  API/Osu/Enums/Ruleset.cs
  API/Osu/Enums/ScoringType.cs
  API/Osu/Enums/Team.cs
  API/Osu/Enums/TeamType.cs
  API/Osu/Multiplayer/IOsuApiService.cs
  API/Osu/Multiplayer/OsuApiMatchData.cs
  API/Osu/Multiplayer/OsuApiService.cs
  API/Osu/OsuEnums.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/MatchScoresRepository.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Interfaces/IMatchScoresRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/SearchService.cs
  API/Services/Interfaces/IPlayerService.cs
  API/Utilities/QueryExtensions.cs
  APITests/AutomationChecks/AutomationChecksTests.cs
  APITests/AutomationChecks/MatchAutomationChecks_Warmups.cs
  APITests/SeedData/SeededGame.cs
  otrAPI.sln.DotSettings
Labels: type:documentation, size/XL, type:code-quality

#246 Automation checks improvements
  API/BackgroundWorkers/OsuMatchDataWorker.cs
  API/DTOs/PlayerStatsDTO.cs
  API/Entities/Game.cs
  API/Enums/VerificationEnums.cs
  API/Osu/AutomationChecks/GameAutomationChecks.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/RepositoryBase.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
  API/Repositories/Interfaces/IRepository.cs
  API/Services/Implementations/PlayerStatsService.cs
  APITests/AutomationChecks/AutomationChecksTests.cs
  APITests/SeedData/SeededGame.cs
Labels: bug, size/XL, area:processing

#228 Add Users Controller
  API/API.csproj
  API/Configurations/MapperProfile.cs
  API/Controllers/MeController.cs
  API/Controllers/UsersController.cs
  API/DTOs/MatchSubmissionStatusDTO.cs
  API/DTOs/OAuthClientDTO.cs
  API/DTOs/UserDTO.cs
  API/DTOs/UserInfoDTO.cs
  API/Entities/GameWinRecord.cs
  API/Entities/MatchDuplicate.cs
  API/Entities/MatchWinRecord.cs
  API/Entities/RateLimitOverrides.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/OtrContext.cs
  API/Program.cs
  API/Repositories/Implementations/HistoryRepositoryBase.cs
  API/Repositories/Implementations/OAuthClientRepository.cs
  API/Repositories/Implementations/RepositoryBase.cs
  API/Repositories/Interfaces/IHistoryRepository.cs
  API/Repositories/Interfaces/IOAuthClientRepository.cs
  API/Repositories/Interfaces/IRepository.cs
  API/Repositories/Interfaces/IUserRepository.cs
  API/Services/Implementations/OAuthClientService.cs
  API/Services/Implementations/UserService.cs
  API/Services/Interfaces/IOAuthClientService.cs
  API/Services/Interfaces/IUserService.cs
  API/Utilities/ClaimsPrincipalExtensions.cs
  API/Utilities/HttpContextExtensions.cs
  API/Utilities/OtrClaimTypes.cs
  API/Utilities/OtrClaims.cs
  APITests/Utilities/OtrClaimsTests.cs
Labels: type:feature, api:breaking-change, size/XL, pr:blocked, area:users

#276 Rename GeneralStats to BaseStats in PlayerStatsDTO
  API/DTOs/PlayerStatsDTO.cs
  API/Services/Implementations/PlayerStatsService.cs
Labels: size/S

#278 Develop
  API/DTOs/PlayerStatsDTO.cs
  API/Services/Implementations/PlayerStatsService.cs
Labels: size/S

#273 Allow searching for tournaments by name and abbreviation
  API/Repositories/Implementations/TournamentsRepository.cs
Labels: size/XS, area:search
