Repository osu-tournament-rating/otr-api, pull requests merged in 2024-05, with the labels that each got.

#281 Add `restart: always` to all compose files
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-staging.yml
Labels: priority:0, size/M

#283 Rename `Winrate` to `WinRate` everywhere
  API/DTOs/BaseStatsDTO.cs
  API/DTOs/LeaderboardFilterDTO.cs
  API/DTOs/LeaderboardPlayerChartDTO.cs
  API/DTOs/ModStatsDTO.cs
  API/ModelBinders/LeaderboardFilterModelBinder.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/LeaderboardService.cs
  API/Services/Implementations/PlayerStatsService.cs
  APITests/MockRepositories/MockMatchStatsRepository.cs
  APITests/Services/LeaderboardServiceTests.cs
Labels: api:breaking-change, size/M

#288 Move `/api/v1/stats/ratingadjustments DELETE` into `/api/v1/stats DELETE`
  API/Controllers/StatsController.cs
  API/Services/Implementations/PlayerStatsService.cs
Labels: api:breaking-change, size/XS, area:stats

#289 Add the ability to enable / disable the whitelist globally
  API/Configurations/AuthConfiguration.cs
  API/Controllers/BeatmapsController.cs
  API/Controllers/ClientsController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/ScreeningController.cs
  API/Controllers/SearchController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Controllers/UsersController.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Middlewares/RequestLoggingMiddleware.cs
  API/Middlewares/WhitelistEnforcementMiddleware.cs
  API/Program.cs
  API/Utilities/ClaimsPrincipalExtensions.cs
  API/Utilities/OtrClaims.cs
  API/example.appsettings.json
  APITests/Utilities/ClaimsPrincipalExtensionsTests.cs
Labels: type:feature, size/L, type:code-quality, area:login, config-change

#290 Code quality improvements to `OAuthHandler`
  API/Controllers/OAuthController.cs
  API/Entities/User.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Handlers/Interfaces/IOAuthHandler.cs
  API/Services/Implementations/OAuthClientService.cs
  API/Services/Interfaces/IOAuthClientService.cs
Labels: type:documentation, size/L, type:code-quality, area:oauth

#292 Fix NullReferenceException
  API/Handlers/Implementations/OAuthHandler.cs
Labels: size/XS

#293 Develop
  API/Configurations/AuthConfiguration.cs
  API/Controllers/BeatmapsController.cs
  API/Controllers/ClientsController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/ScreeningController.cs
  API/Controllers/SearchController.cs
  API/Controllers/StatsController.cs
  API/Controllers/TournamentsController.cs
  API/Controllers/UsersController.cs
  API/DTOs/BaseStatsDTO.cs
  API/DTOs/LeaderboardFilterDTO.cs
  API/DTOs/LeaderboardPlayerChartDTO.cs
  API/DTOs/ModStatsDTO.cs
  API/Entities/User.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Handlers/Interfaces/IOAuthHandler.cs
  API/Middlewares/RequestLoggingMiddleware.cs
  API/Middlewares/WhitelistEnforcementMiddleware.cs
  API/ModelBinders/LeaderboardFilterModelBinder.cs
  API/Program.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Services/Implementations/BaseStatsService.cs
  API/Services/Implementations/LeaderboardService.cs
  API/Services/Implementations/OAuthClientService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Interfaces/IOAuthClientService.cs
  API/Utilities/ClaimsPrincipalExtensions.cs
  API/Utilities/OtrClaims.cs
  API/example.appsettings.json
  APITests/MockRepositories/MockMatchStatsRepository.cs
  APITests/Services/LeaderboardServiceTests.cs
  APITests/Utilities/ClaimsPrincipalExtensionsTests.cs
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-staging.yml
Labels: size/XL

#295 Pipeline restructuring changes: Use trunk-based development
  .github/release.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/L

#291 Use redirect actions for `/me` endpoints
  API/Controllers/MeController.cs
  API/Controllers/StatsController.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IPlayerService.cs
Labels: type:documentation, api:breaking-change, size/L, type:code-quality, area:me, area:stats

#296 Fix permissions on tournaments endpoints
  API/Controllers/TournamentsController.cs
Labels: bug, size/XS, area:tournaments

#300 Add logging to whitelist middleware
  API/Middlewares/WhitelistEnforcementMiddleware.cs
Labels: bug, size/S

#301 Fix bad git ref in staging deployment
  .github/workflows/staging-deploy.yml
Labels: bug, size/XS, config-change

#309 Fix critical match submission issues & recursive error logs
  API/BackgroundWorkers/OsuMatchDataWorker.cs
  API/Services/Implementations/TournamentsService.cs
Labels: bug, priority:0, size/M

#297 Disable lazy loading and use `AsNoTracking` for all table fetches
  API/Repositories/Implementations/BeatmapRepository.cs
  API/Repositories/Implementations/RepositoryBase.cs
  API/Repositories/Implementations/UserRepository.cs
  API/Repositories/Interfaces/IUserRepository.cs
  API/Services/Implementations/UserService.cs
Labels: size/M, pr:blocked, type:performance

#310 Implement strict access control to `User` resources
  API/Authorization/AuthorizationPolicies.cs
  API/Authorization/Handlers/AccessUserResourcesAuthorizationHandler.cs
  API/Authorization/Requirements/AccessUserResourcesRequirement.cs
  API/Controllers/MeController.cs
  API/Controllers/UsersController.cs
  API/Program.cs
Labels: type:feature, size/L, area:me, area:users

#302 Implement caching using CachingFramework.Redis
  API/API.csproj
  API/Configurations/ConnectionStringsConfiguration.cs
  API/Handlers/Implementations/CacheHandler.cs
  API/Handlers/Interfaces/ICacheHandler.cs
  API/Program.cs
  API/Repositories/Implementations/BaseStatsRepository.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/RepositoryBase.cs
  API/Repositories/Implementations/TournamentsRepository.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
  API/Repositories/Interfaces/ITournamentsRepository.cs
  API/Repositories/Interfaces/IUsesCache.cs
  API/Services/Implementations/SearchService.cs
  API/Utilities/CacheUtils.cs
  API/example.appsettings.json
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-staging.yml
Labels: type:feature, size/L, area:search, config-change, type:performance

#313 Fix average mod scores being larger than expected
  API/Entities/Game.cs
  API/Repositories/Implementations/PlayerMatchStatsRepository.cs
Labels: bug, size/S, area:stats

#314 Fix 500 status when `GET` `/matches/{id}` does not exist
  API/Controllers/MatchesController.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Utilities/CreatedAtRouteValuesHelper.cs
Labels: bug, size/S, area:matches

#315 Feature/apimetrics
  API/API.csproj
  API/Program.cs
  docker-compose-prod.yml
  docker-compose-staging.yml
  otel-collector-config.yml
  prometheus.yml
Labels: size/L

#312 Use pagination for `GET` `/matches`
  API/Configurations/MapperProfile.cs
  API/Controllers/MatchesController.cs
  API/DTOs/GameDTO.cs
  API/DTOs/MatchDTO.cs
  API/DTOs/PagedResultDTO.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Repositories/Interfaces/IMatchesRepository.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IMatchesService.cs
Labels: type:feature, api:breaking-change, size/L, area:matches, pr:blocked, type:performance

#319 added the singular missing space
  prometheus.yml
Labels: size/XS

#318 Fix returning invalid data in some cases
  API/BackgroundWorkers/OsuMatchDataWorker.cs
  API/Controllers/MatchesController.cs
  API/Osu/AutomationChecks/GameAutomationChecks.cs
  API/Osu/AutomationChecks/MatchAutomationChecks.cs
  API/Repositories/Implementations/MatchesRepository.cs
  API/Services/Implementations/MatchesService.cs
  APITests/AutomationChecks/AutomationChecksTests.cs
Labels: bug, size/L, area:processing

#320 Rename `MatchWinRecord` properties to match new table schema
  API/DTOs/MatchWinRecordDTO.cs
  API/Repositories/Implementations/MatchWinRecordRepository.cs
Labels: bug, size/M

#322 Allow queries for player stats to use optional ruleset
  API/Controllers/MeController.cs
  API/Controllers/StatsController.cs
  API/DTOs/PlayerStatsDTO.cs
  API/Repositories/Implementations/PlayerRepository.cs
  API/Repositories/Implementations/UserRepository.cs
  API/Repositories/Interfaces/IPlayerRepository.cs
  API/Repositories/Interfaces/IUserRepository.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Implementations/UserService.cs
  API/Services/Interfaces/IPlayerService.cs
  API/Services/Interfaces/IPlayerStatsService.cs
  API/Services/Interfaces/IUserService.cs
  API/Utilities/QueryExtensions.cs
  APITests/Services/LeaderboardServiceTests.cs
Labels: type:feature, api:breaking-change, size/L, area:me, area:stats, pr:blocked

#325 Working initial implementation
  OsuApiClient.Tests/ClientTestService.cs
  OsuApiClient.Tests/OsuApiClient.Tests.csproj
  OsuApiClient.Tests/Program.cs
  OsuApiClient.Tests/Properties/launchSettings.json
  OsuApiClient.Tests/example.appsettings.json
  OsuApiClient/Configurations/Implementations/OsuClientConfiguration.cs
  OsuApiClient/Configurations/Interfaces/IOsuClientConfiguration.cs
  OsuApiClient/Extensions/DictionaryExtensions.cs
  OsuApiClient/Extensions/ServiceExtensions.cs
  OsuApiClient/IOsuClient.cs
  OsuApiClient/Models/AccessCredentialsModel.cs
  OsuApiClient/Models/ModelBase.cs
  OsuApiClient/Net/Authorization/FixedWindowRateLimit.cs
  OsuApiClient/Net/Authorization/OsuCredentials.cs
  OsuApiClient/Net/Constants/Endpoints.cs
  OsuApiClient/Net/Enums/MatchActionType.cs
  OsuApiClient/Net/JsonModels/AccessCredentialsJsonModel.cs
  OsuApiClient/Net/JsonModels/JsonModelBase.cs
  OsuApiClient/Net/Requests/IOsuApiRequest.cs
  OsuApiClient/Net/Requests/OsuApiRequest.cs
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
  OsuApiClient/Net/Requests/RequestHandler/IRequestHandler.cs
  OsuApiClient/OsuApiClient.csproj
  OsuApiClient/OsuClient.cs
  OsuApiClient/OsuClientOptions.cs
  otrAPI.sln
Labels: size/XL
