Repository osu-tournament-rating/otr-api, pull requests merged in 2024-12, with the labels that each got.

#555 fix forum url sanitization
  API/Controllers/TournamentsController.cs
Labels: size/XS

#556 OsuApiClient undo bad mode refactoring
  OsuApiClient/Net/JsonModels/Osu/Beatmaps/BeatmapJsonModel.cs
  OsuApiClient/Net/JsonModels/Osu/Users/Attributes/RankHistoryJsonModel.cs
  OsuApiClient/Net/JsonModels/Osu/Users/Attributes/UserStatisticsVariantJsonModel.cs
Labels: size/XS

#554 Use split query for `GetNeedingProcessingAsync`
  Database/Repositories/Implementations/TournamentsRepository.cs
Labels: size/M, area:tournaments, type:performance, project:Database

#552 Add some useful sql scripts
  scripts/schema.sql
  scripts/sql/maintenance/reset-audits.sql
  scripts/sql/maintenance/reset-automated-checks.sql
Labels: size/L, type:code-quality, type:ops

#557 Add support for patching processing fields on a tournament
  API/Services/Implementations/TournamentsService.cs
Labels: size/S

#561 Fix rejection reason generation for tournaments with pooled beatmaps
  DataWorkerService.Tests/AutomationChecks/Games/GameBeatmapUsageCheckTests.cs
Labels: bug, size/M, type:testing

#551 Legacy code: refactor `BaseStats` usage
  API.Tests/MockRepositories/MockPlayerRatingsRepository.cs
  API.Tests/SeedData/SeededPlayerRatings.cs
  API.Tests/Services/LeaderboardServiceTests.cs
  API/Handlers/Implementations/CacheHandler.cs
  API/Handlers/Interfaces/ICacheHandler.cs
  API/Program.cs
  API/Repositories/Implementations/ApiPlayerRatingsRepository.cs
  API/Repositories/Interfaces/IApiPlayerRatingsRepository.cs
  API/Services/Implementations/FilteringService.cs
  API/Services/Implementations/LeaderboardService.cs
  API/Services/Implementations/PlayerRatingsService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Interfaces/IPlayerRatingsService.cs
  Database/Entities/Processor/PlayerRating.cs
  Database/Repositories/Implementations/PlayerRatingsRepository.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Interfaces/IBaseStatsRepository.cs
  Database/Repositories/Interfaces/IPlayerRatingsRepository.cs
  Database/Repositories/Interfaces/IPlayersRepository.cs
Labels: size/XL, type:code-quality, project:API

#564 Use new qodana secret
  .github/workflows/qodana_code_quality.yml
Labels: type:ops

#562 Refactor primary constructors usage over project
  .editorconfig
  API/Utilities/BitLengthAttribute.cs
Labels: size/XS

#563 Fix broken service injection
  API/Program.cs
Labels: bug, size/S

#559 Expand tournament filtering capabilities
  API/DTOs/MatchRequestQueryDTO.cs
  API/DTOs/TournamentRequestQueryDTO.cs
  API/Repositories/Implementations/ApiTournamentsRepository.cs
  API/Services/Implementations/TournamentsService.cs
  Database/Enums/TournamentQuerySortType.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/L

#566 Use `FirstOrDefault()` instead of `First()`
  DataWorkerService/Services/Implementations/PlayersService.cs
Labels: bug, size/S

#567 Use `LogInformation` for osu!/osu!track updates
  DataWorkerService/Services/Implementations/PlayersService.cs
Labels: bug, size/XS, area:processing, project:DataWorkerService

#565 DataWorkerService performance improvements
  DataWorkerService.Tests/Mocks/MockResolvers.cs
  DataWorkerService.Tests/Stats/MatchStatsProcessorTests.cs
  DataWorkerService/BackgroundServices/TournamentProcessorService.cs
  DataWorkerService/Processors/Matches/MatchAutomationChecksProcessor.cs
  DataWorkerService/Processors/Matches/MatchDataProcessor.cs
  DataWorkerService/Processors/Matches/MatchVerificationProcessor.cs
  DataWorkerService/Processors/Resolvers/Implementations/TournamentProcessorResolver.cs
  DataWorkerService/Processors/Resolvers/Interfaces/ITournamentProcessorResolver.cs
  DataWorkerService/Processors/Tournaments/TournamentAutomationChecksProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentDataProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentStatsProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentVerificationProcessor.cs
Labels: size/L, area:processing, type:performance, project:DataWorkerService

#538 Upgrade all projects to .NET 9.0
  .config/dotnet-tools.json
  .github/workflows/ci-api.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
  API.Dockerfile
  API.Tests/API.Tests.csproj
  API.Tests/Utilities/ClaimsPrincipalExtensionsTests.cs
  API.Utils.Jwt/API.Utils.Jwt.csproj
  API.Utils.Jwt/Options/GeneratorOptions.cs
  API/API.csproj
  API/Controllers/UsersController.cs
  API/DTOs/FilteringRequestDTO.cs
  API/DTOs/FilteringResultDTO.cs
  API/DTOs/GameDTO.cs
  API/DTOs/GameScoreDTO.cs
  API/DTOs/LeaderboardDTO.cs
  API/DTOs/MatchDTO.cs
  API/DTOs/PlayerRatingDTO.cs
  API/DTOs/TournamentDTO.cs
  API/DTOs/TournamentStatsDTO.cs
  API/DTOs/TournamentSubmissionDTO.cs
  DataWorkerService.Dockerfile
  DataWorkerService.Tests/AutomationChecks/IntegratedAutomationChecksTests.cs
  DataWorkerService.Tests/DataWorkerService.Tests.csproj
  DataWorkerService.Tests/Stats/GameStatsProcessorTests.cs
  DataWorkerService/AutomationChecks/Constants.cs
  DataWorkerService/DataWorkerService.csproj
  DataWorkerService/Processors/Games/GameStatsProcessor.cs
  Database/Database.csproj
  Database/Entities/Beatmap.cs
  Database/Entities/Game.cs
  Database/Entities/GameScore.cs
  Database/Entities/Match.cs
  Database/Entities/OAuthClient.cs
  Database/Entities/Player.cs
  Database/Entities/Tournament.cs
  Database/Entities/User.cs
  Database/Repositories/Implementations/BeatmapsRepository.cs
  Database/Repositories/Implementations/UserRepository.cs
  OsuApiClient.Tests/OsuApiClient.Tests.csproj
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
  OsuApiClient/OsuApiClient.csproj
  TestingUtils/TestingUtils.csproj
Labels: size/XL, config-change, type:performance, project:API, project:DataWorkerService, project:Database, project:OsuApiClient, type:ops, project:API.Utils.JWT

#569 Update dotnet action to @v4
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#570 Setup dotnet in deploy job + format
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/M

#560 Add get friend list endpoint
  API/Controllers/UsersController.cs
  API/Services/Implementations/UserService.cs
  API/Services/Interfaces/IUserService.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Implementations/UserRepository.cs
  Database/Repositories/Interfaces/IUserRepository.cs
Labels: size/M

#571 Upgrade various packages to latest version
  API.Tests/API.Tests.csproj
  API/API.csproj
  DataWorkerService.Tests/DataWorkerService.Tests.csproj
  DataWorkerService/DataWorkerService.csproj
  Database/Database.csproj
Labels: size/S

#573 Fix claims for /tournaments GET
  API/Controllers/TournamentsController.cs
Labels: bug, size/XS, area:tournaments, project:API
