Repository osu-tournament-rating/otr-api, pull requests merged in 2025-02, with the labels that each got.

#591 Remove unused classes, improve some data validations
  API.Tests/AutomationChecks/AutomationChecksTests.cs
  API.Tests/AutomationChecks/MatchAutomationChecks_Warmups.cs
  API.Tests/SeedData/SeededBeatmap.cs
  API.Tests/SeedData/SeededBeatmapSet.cs
  API.Tests/SeedData/SeededGame.cs
  API.Tests/SeedData/SeededMatch.cs
  API.Tests/SeedData/SeededMatchRatingStats.cs
  API.Tests/SeedData/SeededMatchScore.cs
  API.Tests/SeedData/SeededPlayer.cs
  API.Tests/SeedData/SeededPlayerMatchStats.cs
  API.Tests/SeedData/SeededTournament.cs
  API.Tests/SeedData/SeededUser.cs
  API.Tests/Utilities/DataAnnotations/BitLengthAttributeTests.cs
  API.Tests/Utilities/DataAnnotations/PercentageAttributeTests.cs
  API.Tests/Utilities/DataAnnotations/PositiveAttributeTests.cs
  API.Tests/_TestData/match_schema.json
  API/Configurations/JwtConfiguration.cs
  API/Controllers/FilteringController.cs
  API/Controllers/GameScoresController.cs
  API/Controllers/GamesController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/TournamentsController.cs
  API/DTOs/GameDTO.cs
  API/DTOs/GameScoreDTO.cs
  API/DTOs/LeaderboardFilterDTO.cs
  API/DTOs/MatchDTO.cs
  API/DTOs/TournamentCompactDTO.cs
  API/Utilities/DataAnnotations/BitLengthAttribute.cs
  API/Utilities/DataAnnotations/PercentageAttribute.cs
  API/Utilities/DataAnnotations/PositiveAttribute.cs
  API/Utilities/Extensions/ModelStateDictionaryExtensions.cs
Labels: size/XXL

#593 API automatic audit blaming
  API/Program.cs
  API/Utilities/AuditBlamingInterceptor.cs
  DataWorkerService/Program.cs
  Database/Entities/AuditEntityBase.cs
  Database/Entities/Interfaces/IAuditEntity.cs
  Database/Interceptors/AuditingInterceptor.cs
  Database/OtrContext.cs
Labels: size/M

#594 API assign verifier navigation
  API/Controllers/TournamentsController.Admin.cs
  API/Services/Implementations/TournamentsService.cs
  API/Services/Interfaces/ITournamentsService.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
Labels: size/S

#596 support DT/HT freemod games
  Database/Entities/Game.cs
Labels: size/S

#600 rewrite the data parser to support new beatmap structure
  .github/workflows/ci-api.yml
  API/Controllers/UsersController.cs
  API/Program.cs
  API/Repositories/Implementations/OAuthClientRepository.cs
  API/Services/Implementations/SearchService.cs
  API/Services/Implementations/TournamentsService.cs
  API/Services/Implementations/UserService.cs
  API/SwaggerGen/Filters/EnumMetadataSchemaFilter.cs
  API/SwaggerGen/Filters/SecurityMetadataOperationFilter.cs
  DataWorkerService/AutomationChecks/Matches/MatchHeadToHeadCheck.cs
  DataWorkerService/Processors/Games/GameStatsProcessor.cs
  DataWorkerService/Processors/Matches/MatchStatsProcessor.cs
  DataWorkerService/Processors/Resolvers/Implementations/ProcessorResolver.cs
  DataWorkerService/Processors/Tournaments/TournamentDataProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentStatsProcessor.cs
  DataWorkerService/Services/Implementations/OsuApiDataParserService.cs
  DataWorkerService/Services/Interfaces/IOsuApiDataParserService.cs
  DataWorkerService/Utilities/MatchCostCalculator.cs
  Database/Interceptors/AuditingInterceptor.cs
  Database/Repositories/Implementations/BeatmapsRepository.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Implementations/RepositoryBase.cs
  OsuApiClient/Domain/Osu/Multiplayer/MatchInfo.cs
  OsuApiClient/Net/JsonModels/Osu/Multiplayer/MatchInfoJsonModel.cs
  OsuApiClient/OsuClient.cs
Labels: size/XL

#602 Snake case by default database refactor
  API/Configurations/MapperProfile.cs
  API/DTOs/BeatmapDTO.cs
  API/DTOs/BeatmapSetCompactDTO.cs
  API/DTOs/BeatmapSetDTO.cs
  API/Program.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Implementations/SearchService.cs
  API/Services/Implementations/UserSettingsService.cs
  DataWorkerService/Program.cs
  DataWorkerService/Services/Implementations/OsuApiDataParserService.cs
  DataWorkerService/Services/Implementations/PlayersService.cs
  Database/Database.csproj
  Database/Entities/AdminNoteEntityBase.cs
  Database/Entities/AuditEntityBase.cs
  Database/Entities/Beatmap.cs
  Database/Entities/BeatmapAttributes.cs
  Database/Entities/BeatmapSet.cs
  Database/Entities/EntityBase.cs
  Database/Entities/Game.cs
  Database/Entities/GameAdminNote.cs
  Database/Entities/GameAudit.cs
  Database/Entities/GameScore.cs
  Database/Entities/GameScoreAdminNote.cs
  Database/Entities/GameScoreAudit.cs
  Database/Entities/GameWinRecord.cs
  Database/Entities/Match.cs
  Database/Entities/MatchAdminNote.cs
  Database/Entities/MatchAudit.cs
  Database/Entities/MatchWinRecord.cs
  Database/Entities/OAuthClient.cs
  Database/Entities/OAuthClientAdminNote.cs
  Database/Entities/Player.cs
  Database/Entities/PlayerAdminNote.cs
  Database/Entities/PlayerHighestRanks.cs
  Database/Entities/PlayerMatchStats.cs
  Database/Entities/PlayerOsuRulesetData.cs
  Database/Entities/PlayerTournamentStats.cs
  Database/Entities/Processor/PlayerRating.cs
  Database/Entities/Processor/RatingAdjustment.cs
  Database/Entities/Tournament.cs
  Database/Entities/TournamentAdminNote.cs
  Database/Entities/TournamentAudit.cs
  Database/Entities/UpdateableEntityBase.cs
  Database/Entities/User.cs
  Database/Entities/UserSettings.cs
  Database/Migrations/20250219161426_Initial.Designer.cs
  Database/Migrations/20250219161426_Initial.cs
  Database/Migrations/OtrContextModelSnapshot.cs
  Database/OtrContext.cs
  Database/OtrDbContextFactory.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Implementations/UserSettingsRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
  OsuApiClient/Domain/Osu/Beatmaps/BeatmapsetExtended.cs
  TestingUtils/SeededData/SeededBeatmap.cs
  TestingUtils/SeededData/SeededPlayer.cs
Labels: size/XXL

#603 Update PlayerCompactDTO to match entity
  API/DTOs/PlayerCompactDTO.cs
  Database/Entities/Player.cs
Labels: bug, size/XS

#609 Fix DateTime.Now usage
  DataWorkerService/BackgroundServices/TournamentProcessorService.cs
Labels: size/XS

#605 Add `accept-all-pre.sql` maintenance script
  scripts/sql/dev/accept-all-pre.sql
Labels: size/XS
