Repository osu-tournament-rating/otr-api, pull requests merged in 2025-07, with the labels that each got.

#761 Remove access token refresh
  API/Program.cs
Labels: size/M

#762 Anonymize more routes, remove /me redirect
  API/Controllers/AdminNotesController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/MeController.cs
  API/Controllers/PlatformStatsController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/TournamentsController.cs
Labels: size/M

#763 Fix grafana issues
  cfg/docker-compose.yml
  cfg/loki.yml
Labels: size/S

#764 Fix loki configuration
  .github/workflows/deploy.yml
  cfg/loki.yml
Labels: bug, size/S

#765 feat: API key authorization policy
  .editorconfig
  API/Authorization/AuthorizationPolicies.cs
  API/Authorization/Handlers/ApiKeyAuthorizationHandler.cs
  API/Authorization/Requirements/ApiKeyAuthorizationRequirement.cs
  API/Configurations/AuthConfiguration.cs
  API/Controllers/AdminNotesController.cs
  API/Controllers/DiagnosticsController.cs
  API/Controllers/FilteringController.cs
  API/Controllers/LeaderboardsController.cs
  API/Controllers/MatchesController.cs
  API/Controllers/PlatformStatsController.cs
  API/Controllers/PlayersController.cs
  API/Controllers/TournamentsController.cs
  API/Program.cs
  API/Properties/launchSettings.json
  API/example.appsettings.json
Labels: type:feature, size/L, config-change
