Repository osu-tournament-rating/otr-api, pull requests merged in 2025-05, with the labels that each got.

#659 Code quality refactor of PlayerService and FilteringService
  API.Tests/Utilities/EnumUtilsTests.cs
  API/Controllers/FilteringController.cs
  API/DTOs/FilteringRequestDTO.cs
  API/DTOs/FilteringResultDTO.cs
  API/DTOs/PlayerFilteringResultDTO.cs
  API/Services/Implementations/FilteringService.cs
  API/Services/Implementations/PlayerService.cs
  API/Services/Interfaces/IFilteringService.cs
  API/Services/Interfaces/IPlayerService.cs
  API/Utilities/DataAnnotations/SupportedRulesetAttribute.cs
  Common/Enums/FilteringFailReason.cs
  Common/Enums/FilteringResult.cs
  Common/Utilities/EnumUtils.cs
  Database/Entities/Game.cs
  Database/Entities/GameScore.cs
  Database/Entities/Match.cs
  Database/Entities/Tournament.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Interfaces/IPlayersRepository.cs
Labels: size/L, type:code-quality

#661 Telemetry Improvements
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
  API/API.csproj
  API/Configurations/ConnectionStringsConfiguration.cs
  API/Program.cs
  cfg/api.env.example
  cfg/dataworkerservice.env.example
  cfg/docker-compose-prod.yml
  cfg/docker-compose-staging.yml
  cfg/loki.yml
  cfg/minio.env.example
  cfg/otel-collector-config.yml
  cfg/prometheus.yml
  cfg/tempo.yml
Labels: type:feature, size/L, config-change

#678 Update staging deploy and loki/tempo configs
  .github/workflows/staging-deploy.yml
  cfg/loki.yml
  cfg/tempo.yml
Labels: size/M

#679 Use read-only volumes for yml files
  cfg/docker-compose-staging.yml
Labels: size/XS

#668 Add endpoint to merge matches
  API/Controllers/MatchesController.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IMatchesService.cs
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Repositories/Interfaces/IMatchesRepository.cs
Labels: type:feature, size/M

#680 fix loki/tempo actions
  .github/workflows/staging-deploy.yml
Labels: size/S

#684 Add terms of use to OpenApiInfo
  API/Program.cs
Labels: size/XS

#677 Global tournaments stats
  API.Tests/Utilities/RatingUtilsTests.cs
  API/DTOs/TournamentPlatformStatsDTO.cs
  API/Services/Implementations/PlayerRatingsService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Implementations/TournamentPlatformStatsService.cs
  API/Utilities/RatingUtils.cs
  Common/Constants/RatingConstants.cs
  Common/Utilities/EnumUtils.cs
  DataWorkerService.Tests/Stats/MatchStatsProcessorTests.cs
  DataWorkerService/AutomationChecks/Matches/MatchEndTimeCheck.cs
  Database/Repositories/Implementations/PlayerRatingsRepository.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
Labels: size/M

#673 Add support for cookie-based authentication
  API.Tests/Utilities/ClaimsPrincipalExtensionsTests.cs
  API.Utils.Jwt/Options/GeneratorOptions.cs
  API.Utils.Jwt/Options/OptionsExtensions.cs
  API.Utils.Jwt/Program.cs
  API/Authorization/OtrClaims.cs
  API/Configurations/AuthConfiguration.cs
  API/Controllers/AuthController.cs
  API/Controllers/ClientsController.cs
  API/Controllers/MeController.cs
  API/Controllers/OAuthController.cs
  API/Controllers/UsersController.cs
  API/DTOs/AccessCredentialsDTO.cs
  API/Handlers/Implementations/OAuthHandler.cs
  API/Handlers/Interfaces/IOAuthHandler.cs
  API/Program.cs
  API/Services/Implementations/JwtService.cs
  API/Services/Implementations/OAuthClientService.cs
  API/Services/Implementations/UsersService.cs
  API/Services/Interfaces/IJwtService.cs
  API/Services/Interfaces/IOAuthClientService.cs
  API/Services/Interfaces/IUsersService.cs
  API/Utilities/Extensions/ClaimsPrincipalExtensions.cs
  API/example.appsettings.json
  OsuApiClient/IOsuClient.cs
  OsuApiClient/Net/Authorization/OsuCredentials.cs
  OsuApiClient/OsuClient.cs
Labels: type:feature, api:breaking-change, size/XXL, config-change

#686 Disable authorization for AuthController
  API/Controllers/AuthController.cs
Labels: bug, size/XS

#688 sync prod and staging compose files
  cfg/docker-compose-prod.yml
  cfg/docker-compose-staging.yml
Labels: size/M

#690 Update osu client config, remove excess console logs
  API/Configurations/OsuConfiguration.cs
  API/Program.cs
  API/example.appsettings.json
  DataWorkerService/Configurations/ConnectionStringsConfiguration.cs
  DataWorkerService/Configurations/OsuConfiguration.cs
  DataWorkerService/Program.cs
  DataWorkerService/example.appsettings.json
  OsuApiClient.Tests/Program.cs
  OsuApiClient.Tests/example.appsettings.json
  OsuApiClient/Configurations/Implementations/OsuClientConfiguration.cs
  OsuApiClient/Configurations/Interfaces/IOsuClientConfiguration.cs
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
Labels: size/L

#691 Add missing production CI configurations
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
  API/Program.cs
Labels: bug, size/M

#696 Add persistent keys, add more fields to search results
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
  API/API.csproj
  API/Configurations/MapperProfile.cs
  API/DTOs/MatchSearchResultDTO.cs
  API/DTOs/PlayerSearchResultDTO.cs
  API/Program.cs
  API/Services/Implementations/SearchService.cs
  API/example.appsettings.json
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Interfaces/IMatchesRepository.cs
Labels: size/M

#697 TournamentDTO & TournamentSearchResultDTO improvements
  API/Configurations/MapperProfile.cs
  API/DTOs/PlayerTournamentStatsBaseDTO.cs
  API/DTOs/PlayerTournamentStatsDTO.cs
  API/DTOs/TournamentDTO.cs
  API/DTOs/TournamentSearchResultDTO.cs
  API/Services/Implementations/SearchService.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
Labels: type:feature, size/L

#698 Fix grant type of osu credentials request
  OsuApiClient/OsuClient.cs
Labels: size/XS

#699 Add missing include statements and return type docs for `/tournaments/{id}/beatmaps`
  API/Controllers/TournamentsController.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
Labels: size/S

#702 Telemetry hotfix
  cfg/docker-compose-prod.yml
  cfg/docker-compose-staging.yml
  cfg/loki.yml
  cfg/tempo.yml
Labels: size/M

#682 Global rating stats
  API/DTOs/PlatformStatsDTO.cs
  API/DTOs/RatingPlatformStatsDTO.cs
  API/Program.cs
  API/Services/Implementations/PlatformStatsService.cs
  API/Services/Implementations/PlayerRatingsService.cs
  API/Services/Implementations/RatingPlatformStatsService.cs
  API/Services/Interfaces/IPlayerRatingsService.cs
  API/Services/Interfaces/IRatingPlatformStatsService.cs
  API/Services/Interfaces/ITournamentPlatformStatsService.cs
  Common/Utilities/EnumUtils.cs
  Database/Repositories/Implementations/PlayerRatingsRepository.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/IPlayerRatingsRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
Labels: size/L

#707 Hotfix rejection endpoint
  Database/Repositories/Implementations/TournamentsRepository.cs
Labels: size/M

#709 Update dockerfiles
  API.Dockerfile
  DataWorkerService.Dockerfile
Labels: size/M

#712 Patch sql scripts
  scripts/sql/maintenance/cascade-rejections.sql
  scripts/sql/maintenance/reset-automated-checks.sql
Labels: size/M

#713 Efficiency improvements with match querying & entity tracking
  API/Services/Implementations/MatchesService.cs
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Interfaces/IMatchesRepository.cs
Labels: size/M

#715 Clear warnings from verified data, refactor parent rejection cascade logic
  API.Tests/Utilities/EnumUtilsTests.cs
  API/Services/Implementations/GamesService.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Implementations/TournamentsService.cs
  Common/Utilities/EnumUtils.cs
  Common/Utilities/Extensions/VerificationStatusExtensions.cs
  DataWorkerService/Processors/Games/GameVerificationProcessor.cs
  DataWorkerService/Processors/Matches/MatchVerificationProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentVerificationProcessor.cs
  Database/Entities/Game.cs
  Database/Entities/GameScore.cs
  Database/Entities/Interfaces/IProcessableEntity.cs
  Database/Entities/Match.cs
  Database/Entities/Tournament.cs
  Database/Repositories/Implementations/GamesRepository.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/IGamesRepository.cs
  Database/Repositories/Interfaces/ITournamentsRepository.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/L

#716 Fix cookie key persistence
  API/Configurations/AuthConfiguration.cs
  API/Handlers/Implementations/CacheHandler.cs
  API/Program.cs
  API/example.appsettings.json
Labels: size/L

#719 Fix data protection & HTTPS redirects
  API/Configurations/AuthConfiguration.cs
  API/HealthChecks/DataProtectionHealthCheck.cs
  API/HealthChecks/DatabaseHealthCheck.cs
  API/HealthChecks/RedisHealthCheck.cs
  API/Program.cs
Labels: size/L

#720 Add endpoint to delete player scores from match
  API/Controllers/MatchesController.cs
  API/Services/Implementations/MatchesService.cs
  API/Services/Interfaces/IMatchesService.cs
  Database/Repositories/Implementations/GameScoresRepository.cs
  Database/Repositories/Interfaces/IGameScoresRepository.cs
Labels: type:feature, size/M
