Repository osu-tournament-rating/otr-api, pull requests merged in 2025-03, with the labels that each got.

#617 Final edits I forgor to merge
  API/DTOs/PlayerFrequencyDTO.cs
  API/DTOs/PlayerModStatsDTO.cs
  Common/Enums/Enums/Verification/MatchWarningFlags.cs
  Common/Enums/Enums/Verification/TournamentRejectionReason.cs
  Common/Enums/Enums/Verification/VerificationStatus.cs
  Database/Entities/GameRoster.cs
  Database/Entities/Interfaces/IRoster.cs
  Database/Entities/MatchRoster.cs
  Database/Repositories/Implementations/PlayersRepository.cs
  Database/Repositories/Interfaces/IPlayersRepository.cs
Labels: size/M

#624 Update/add commonly used scripts
  scripts/sql/dev/reject-matches-with-no-games.sql
  scripts/sql/dev/view-all-processing-statuses.sql
  scripts/sql/maintenance/delete-audits.sql
  scripts/sql/maintenance/reset-automated-checks.sql
  scripts/sql/maintenance/reset-stats.sql
Labels: size/L

#610 Exclude empty matches from tournaments threshold calculation in checks
  API/API.csproj
  DataWorkerService.Tests/AutomationChecks/Tournaments/TournamentMatchCountCheckTests.cs
  DataWorkerService/AutomationChecks/Tournaments/TournamentMatchCountCheck.cs
Labels: size/L

#622 Fix LowGameCount warning logic
  DataWorkerService.Tests/AutomationChecks/Matches/MatchGameCountCheckTests.cs
  DataWorkerService/AutomationChecks/Matches/MatchGameCountCheck.cs
Labels: size/XS

#623 Disable forced collection expressions
  .editorconfig
Labels: size/XS

#626 Final DataWorkerService fixes for production release
  DataWorkerService/Processors/Matches/MatchStatsProcessor.cs
  DataWorkerService/Processors/Tournaments/TournamentStatsProcessor.cs
Labels: size/M

#627 Add thread safety for external API fetch operations
  DataWorkerService/BackgroundServices/TournamentProcessorService.cs
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
Labels: size/S, area:processing, type:performance

#621 Games integrity checks improvements
  Common/Enums/Enums/Verification/GameRejectionReason.cs
  Common/Enums/Enums/Verification/MatchWarningFlags.cs
  Common/Utilities/Extensions/VerificationStatusExtensions.cs
  DataWorkerService.Tests/AutomationChecks/Games/GameScoreCountCheckTests.cs
  DataWorkerService.Tests/AutomationChecks/Matches/MatchGameCountCheckTests.cs
  DataWorkerService.Tests/AutomationChecks/Matches/MatchTeamsIntegrityCheckTests.cs
  DataWorkerService.Tests/Mocks/MockResolvers.cs
  DataWorkerService.Tests/Stats/GameStatsProcessorTests.cs
  DataWorkerService.Tests/Stats/MatchStatsProcessorTests.cs
  DataWorkerService/AutomationChecks/Games/GameScoreCountCheck.cs
  DataWorkerService/AutomationChecks/Matches/MatchGameCountCheck.cs
  DataWorkerService/AutomationChecks/Matches/MatchHeadToHeadCheck.cs
  DataWorkerService/AutomationChecks/Matches/MatchTeamsIntegrityCheck.cs
  DataWorkerService/AutomationChecks/Tournaments/TournamentMatchCountCheck.cs
  DataWorkerService/Processors/Games/GameStatsProcessor.cs
  DataWorkerService/Processors/Matches/MatchStatsProcessor.cs
  DataWorkerService/Program.cs
  DataWorkerService/Utilities/RostersHelper.cs
Labels: size/XL

#631 Improve tournament list query filtering
  API/DTOs/TournamentRequestQueryDTO.cs
  Common/Enums/Enums/TournamentQuerySortType.cs
  Database/Utilities/Extensions/QueryExtensions.cs
Labels: size/S

#632 Replace semaphore with global mutex
  OsuApiClient/Net/Authorization/FixedWindowRateLimit.cs
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
Labels: bug, size/M

#629 Leaderboard API refactor
  API.Tests/MockRepositories/MockPlayerRatingsRepository.cs
  API.Tests/SeedData/SeededPlayerRatings.cs
  API.Tests/Utilities/LeaderboardExtensionsTests.cs
  API/Configurations/MapperProfile.cs
  API/Controllers/LeaderboardsController.cs
  API/DTOs/Interfaces/IPaginated.cs
  API/DTOs/LeaderboardDTO.cs
  API/DTOs/LeaderboardFilterDTO.cs
  API/DTOs/LeaderboardRequestQueryDTO.cs
  API/DTOs/LeaderboardTierFilterDTO.cs
  API/DTOs/PlayerRatingStatsDTO.cs
  API/Services/Implementations/PlayerRatingsService.cs
  API/Services/Implementations/PlayerStatsService.cs
  API/Services/Interfaces/IPlayerRatingsService.cs
  API/Services/Interfaces/IPlayerStatsService.cs
  API/Utilities/AdminNotes/AdminNoteRouteTarget.cs
  API/Utilities/Extensions/LeaderboardExtensions.cs
  API/Utilities/RatingUtils.cs
  Common/Common.csproj
  Common/Enums/LeaderboardChartType.cs
  Common/Rating/RatingConstants.cs
  Database/Database.csproj
  Database/Entities/PlayerTournamentStats.cs
  Database/Models/LeaderboardFilter.cs
  Database/Models/LeaderboardTierFilter.cs
  Database/Repositories/Implementations/MatchesRepository.cs
  Database/Repositories/Implementations/PlayerRatingsRepository.cs
  Database/Repositories/Implementations/PlayerTournamentStatsRepository.cs
  Database/Repositories/Implementations/TournamentsRepository.cs
  Database/Repositories/Interfaces/IPlayerRatingsRepository.cs
  Database/Repositories/Interfaces/IPlayerTournamentStatsRepository.cs
  Database/Utilities/Extensions/CommonQueryExtensions.cs
Labels: size/XXL, type:code-quality, area:leaderboards, type:performance

#630 Refactor admin note routes into a single dynamic controller
  API/Controllers/AdminNotesController.cs
  API/Controllers/GameScoresController.Admin.cs
  API/Controllers/GameScoresController.cs
  API/Controllers/GamesController.Admin.cs
  API/Controllers/GamesController.cs
  API/Controllers/MatchesController.Admin.cs
  API/Controllers/MatchesController.cs
  API/Controllers/PlayersController.Admin.cs
  API/Controllers/PlayersController.cs
  API/Controllers/TournamentsController.Admin.cs
  API/Controllers/TournamentsController.cs
  API/Program.cs
  API/Services/Implementations/AdminNoteService.cs
  API/Services/Implementations/DynamicAdminNoteService.cs
  API/Services/Interfaces/IAdminNoteService.cs
  API/SwaggerGen/Filters/EnumMetadataSchemaFilter.cs
  API/SwaggerGen/Filters/OverrideSchemaFilter.cs
  API/Utilities/AdminNotes/AdminNoteRouteTarget.cs
  API/Utilities/AdminNotes/AdminNotesHelper.cs
  API/Utilities/AdminNotes/ValidateAdminNoteControllerRouteAttribute.cs
  Common/Common.csproj
  Database/Repositories/Implementations/AdminNoteRepositoryBase.cs
  Database/Repositories/Interfaces/IAdminNoteRepository.cs
  otrAPI.sln.DotSettings
Labels: size/XXL

#635 Add distributed locking support for osu! requests
  API/API.csproj
  API/Program.cs
  DataWorkerService/Configurations/ConnectionStringsConfiguration.cs
  DataWorkerService/DataWorkerService.csproj
  DataWorkerService/Program.cs
  DataWorkerService/example.appsettings.json
  OsuApiClient/Net/Requests/RequestHandler/DefaultRequestHandler.cs
  OsuApiClient/OsuApiClient.csproj
Labels: bug, size/M, config-change, type:performance, project:API, project:DataWorkerService, project:OsuApiClient

#636 Fix fatal collection mismatch during roster generation
  DataWorkerService/Utilities/RostersHelper.cs
Labels: bug, size/XS, area:stats, area:processing, project:DataWorkerService

#638 Update new feature template
  .github/ISSUE_TEMPLATE/new-feature.md
Labels: size/XS
